[package]
name = "Eurium"
version = "1.0.0"
authors = ["Eurium Foundation"]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[addresses]
eurium_addr = "_"
